// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Vejledningsbooking.Persistence.Data;

namespace Vejledningsbooking.Persistence.Migrations
{
    [DbContext(typeof(BookingContext))]
    [Migration("20210922063906_SQL_Migration")]
    partial class SQL_Migration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Vejledningsbooking.Domain.Booking", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BookingVindueId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SlutTidspunkt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartTidspunkt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("StuderendeId")
                        .HasColumnType("int");

                    b.HasKey("BookingId");

                    b.HasIndex("BookingVindueId");

                    b.HasIndex("StuderendeId");

                    b.ToTable("Booking");
                });

            modelBuilder.Entity("Vejledningsbooking.Domain.BookingVindue", b =>
                {
                    b.Property<int>("BookingVindueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("HoldId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<DateTime>("SlutTidspunkt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartTidspunkt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UnderviserId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("BookingVindueId");

                    b.HasIndex("UnderviserId", "HoldId");

                    b.ToTable("BookingVindue");
                });

            modelBuilder.Entity("Vejledningsbooking.Domain.Hold", b =>
                {
                    b.Property<int>("HoldId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("HoldId");

                    b.ToTable("Hold");
                });

            modelBuilder.Entity("Vejledningsbooking.Domain.Kalender", b =>
                {
                    b.Property<int?>("UnderviserId")
                        .HasColumnType("int");

                    b.Property<int?>("HoldId")
                        .HasColumnType("int");

                    b.HasKey("UnderviserId", "HoldId");

                    b.HasIndex("HoldId");

                    b.ToTable("Kalender");
                });

            modelBuilder.Entity("Vejledningsbooking.Domain.Studerende", b =>
                {
                    b.Property<int>("StuderendeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Navn")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StuderendeId");

                    b.ToTable("Studerende");
                });

            modelBuilder.Entity("Vejledningsbooking.Domain.Underviser", b =>
                {
                    b.Property<int>("UnderviserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Navn")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UnderviserId");

                    b.ToTable("Underviser");
                });

            modelBuilder.Entity("Vejledningsbooking.Domain.Booking", b =>
                {
                    b.HasOne("Vejledningsbooking.Domain.BookingVindue", "BookingVindue")
                        .WithMany("Bookinger")
                        .HasForeignKey("BookingVindueId");

                    b.HasOne("Vejledningsbooking.Domain.Studerende", "Studerende")
                        .WithMany("Bookinger")
                        .HasForeignKey("StuderendeId");

                    b.Navigation("BookingVindue");

                    b.Navigation("Studerende");
                });

            modelBuilder.Entity("Vejledningsbooking.Domain.BookingVindue", b =>
                {
                    b.HasOne("Vejledningsbooking.Domain.Kalender", "Kalender")
                        .WithMany("BookingVinduer")
                        .HasForeignKey("UnderviserId", "HoldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kalender");
                });

            modelBuilder.Entity("Vejledningsbooking.Domain.Kalender", b =>
                {
                    b.HasOne("Vejledningsbooking.Domain.Hold", "Hold")
                        .WithMany("Kalendere")
                        .HasForeignKey("HoldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vejledningsbooking.Domain.Underviser", "Underviser")
                        .WithMany("Kalendere")
                        .HasForeignKey("UnderviserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hold");

                    b.Navigation("Underviser");
                });

            modelBuilder.Entity("Vejledningsbooking.Domain.BookingVindue", b =>
                {
                    b.Navigation("Bookinger");
                });

            modelBuilder.Entity("Vejledningsbooking.Domain.Hold", b =>
                {
                    b.Navigation("Kalendere");
                });

            modelBuilder.Entity("Vejledningsbooking.Domain.Kalender", b =>
                {
                    b.Navigation("BookingVinduer");
                });

            modelBuilder.Entity("Vejledningsbooking.Domain.Studerende", b =>
                {
                    b.Navigation("Bookinger");
                });

            modelBuilder.Entity("Vejledningsbooking.Domain.Underviser", b =>
                {
                    b.Navigation("Kalendere");
                });
#pragma warning restore 612, 618
        }
    }
}
