// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Vejledningsbooking.Persistence;

namespace Vejledningsbooking.Persistence.Migrations
{
    [DbContext(typeof(BookingContext))]
    partial class BookingContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Vejledningsbooking.Domain.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BookingVindueId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime>("SlutTidspunkt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartTidspunkt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("StuderendeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookingVindueId");

                    b.HasIndex("StuderendeId");

                    b.ToTable("Booking");
                });

            modelBuilder.Entity("Vejledningsbooking.Domain.BookingVindue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("KalenderId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SlutTidspunkt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartTidspunkt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UnderviserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KalenderId");

                    b.HasIndex("UnderviserId");

                    b.ToTable("BookingVindue");
                });

            modelBuilder.Entity("Vejledningsbooking.Domain.Hold", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("Id");

                    b.ToTable("Hold");
                });

            modelBuilder.Entity("Vejledningsbooking.Domain.Kalender", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("HoldId")
                        .HasColumnType("int");

                    b.Property<int?>("UnderviserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HoldId");

                    b.HasIndex("UnderviserId");

                    b.ToTable("Kalender");
                });

            modelBuilder.Entity("Vejledningsbooking.Domain.Studerende", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Navn")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Studerende");
                });

            modelBuilder.Entity("Vejledningsbooking.Domain.Underviser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Navn")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Underviser");
                });

            modelBuilder.Entity("Vejledningsbooking.Domain.Booking", b =>
                {
                    b.HasOne("Vejledningsbooking.Domain.BookingVindue", "BookingVindue")
                        .WithMany("Bookinger")
                        .HasForeignKey("BookingVindueId");

                    b.HasOne("Vejledningsbooking.Domain.Studerende", "Studerende")
                        .WithMany("Bookinger")
                        .HasForeignKey("StuderendeId");

                    b.Navigation("BookingVindue");

                    b.Navigation("Studerende");
                });

            modelBuilder.Entity("Vejledningsbooking.Domain.BookingVindue", b =>
                {
                    b.HasOne("Vejledningsbooking.Domain.Kalender", "Kalender")
                        .WithMany("BookingVinduer")
                        .HasForeignKey("KalenderId");

                    b.HasOne("Vejledningsbooking.Domain.Underviser", "Underviser")
                        .WithMany("BookingVinduer")
                        .HasForeignKey("UnderviserId");

                    b.Navigation("Kalender");

                    b.Navigation("Underviser");
                });

            modelBuilder.Entity("Vejledningsbooking.Domain.Kalender", b =>
                {
                    b.HasOne("Vejledningsbooking.Domain.Hold", "Hold")
                        .WithMany("Kalendere")
                        .HasForeignKey("HoldId");

                    b.HasOne("Vejledningsbooking.Domain.Underviser", "Underviser")
                        .WithMany("Kalendere")
                        .HasForeignKey("UnderviserId");

                    b.Navigation("Hold");

                    b.Navigation("Underviser");
                });

            modelBuilder.Entity("Vejledningsbooking.Domain.BookingVindue", b =>
                {
                    b.Navigation("Bookinger");
                });

            modelBuilder.Entity("Vejledningsbooking.Domain.Hold", b =>
                {
                    b.Navigation("Kalendere");
                });

            modelBuilder.Entity("Vejledningsbooking.Domain.Kalender", b =>
                {
                    b.Navigation("BookingVinduer");
                });

            modelBuilder.Entity("Vejledningsbooking.Domain.Studerende", b =>
                {
                    b.Navigation("Bookinger");
                });

            modelBuilder.Entity("Vejledningsbooking.Domain.Underviser", b =>
                {
                    b.Navigation("BookingVinduer");

                    b.Navigation("Kalendere");
                });
#pragma warning restore 612, 618
        }
    }
}
